# Generated by Django 3.2 on 2023-03-06 21:44

from django.db import migrations, models
import main.models.banner


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=main.models.banner.banner_image)),
                ('type', models.CharField(choices=[('Static', 'Static'), ('Category', 'Category'), ('Product', 'Product'), ('Many Products', 'ManyProducts')], default='Static', max_length=50)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('live', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
