# Generated by Django 3.2 on 2023-03-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='position',
            field=models.CharField(choices=[('up_main_page', 'Up Main Page'), ('down_main_page', 'Down Main Page')], default='up_main_page', max_length=50),
        ),
    ]
