# Generated by Django 3.2 on 2023-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='type',
            field=models.CharField(choices=[('Static', 'Static'), ('Product', 'Product'), ('special_offers', 'Special Offers')], default='Static', max_length=50),
        ),
    ]
