# Generated by Django 3.2 on 2023-03-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_currency_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='position',
        ),
    ]
