# Generated by Django 3.2 on 2023-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_banners_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='order',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
