# Generated by Django 3.2 on 2023-03-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shippingfee'),
        ('orders', '0002_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.PositiveIntegerField(choices=[(1, 'On Delivery')], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shippingfee'),
        ),
    ]
