# Generated by Django 3.2 on 2023-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230307_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.PositiveIntegerField(choices=[(1, 'On Delivery')], default=1),
        ),
    ]
