# Generated by Django 3.2 on 2023-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appversion'),
        ('users', '0010_user_registered'),
        ('orders', '0004_alter_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shippingfee'),
        ),
    ]
