# Generated by Django 3.2 on 2023-03-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Currency',
            new_name='currency',
        ),
    ]
