# Generated by Django 3.2 on 2023-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_currency_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
