# Generated by Django 3.2 on 2023-03-06 08:00

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and -/_ only.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, digits, -,_', regex='^[a-zA-Z0-9\\-_ ]{4,100}$')], verbose_name='username')),
                ('name', models.CharField(help_text='should be alpha only with max length 50', max_length=150, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Worker')], default=2)),
                ('country', models.CharField(default='Egypt', max_length=50)),
                ('city', models.CharField(default='Cairo', max_length=50)),
                ('address_1', models.CharField(default='Address 1', max_length=100)),
                ('address_2', models.CharField(default='Address 2 (street, Building)', max_length=100)),
                ('location', models.JSONField(blank=True, null=True)),
                ('user_token', models.CharField(blank=True, max_length=500, null=True)),
                ('last_order', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
