# Generated by Django 3.2 on 2023-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
