# Generated by Django 3.2 on 2023-03-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230308_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='has_sub_category',
        ),
    ]
