# Generated by Django 3.2 on 2023-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Big unit name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_unit',
            field=models.CharField(default=1, max_length=100, verbose_name='Unit name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='small_unit_discount_max_quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Max quantity user have to buy if there is a discount on the Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_unit_price',
            field=models.FloatField(default=0, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_unit_price_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount price for the unit'),
        ),
    ]
